# This file was generated by GoReleaser. DO NOT EDIT.
cask "bothy" do
  version "0.10.0"

  on_macos do
    on_arm do
      sha256 "7724ebe65dff8775629c4aeecf3f44a224ca9fc3a12580f775170e2046bf3f92"
      url "https://github.com/bspeelm/bothy/releases/download/v#{version}/bothy_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "2bfabe1807717f271a02ac9d6cd0801a472d1350a73258a3a792911aecb41701"
      url "https://github.com/bspeelm/bothy/releases/download/v#{version}/bothy_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "6934d4f8b19912bc16aaa53a00e00a6a9a8a7644f89dce350a78325ca15effc7"
      url "https://github.com/bspeelm/bothy/releases/download/v#{version}/bothy_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "fe1df22d36a12b604ae745c23238e3bdfbe4ed937b8cb78c19289543586f3aae"
      url "https://github.com/bspeelm/bothy/releases/download/v#{version}/bothy_linux_amd64.tar.gz"
    end
  end

  name "bothy"
  desc "A turn-key terminal workspace built from tools you already trust"
  homepage "https://github.com/bspeelm/bothy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bothy"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bothy"]
    end
  end

  # No zap stanza required
end
