# This file was generated by GoReleaser. DO NOT EDIT.
cask "bothy" do
  version "0.13.0"

  on_macos do
    on_arm do
      sha256 "585324691b91c2965f2c46318fb7c0fa9e72d484e187120b633f69c79ae96c6c"
      url "https://github.com/bspeelm/bothy/releases/download/v#{version}/bothy_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "6755dc52d7a77f614a2c9c0b452e65d75296fed25e95ca4c1360343b329e3ec0"
      url "https://github.com/bspeelm/bothy/releases/download/v#{version}/bothy_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ca710ae2ea70dba250a85c45cebed6545ba4b585c9ab0f0f025b670899365341"
      url "https://github.com/bspeelm/bothy/releases/download/v#{version}/bothy_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c83958b785a53bf0f90b356217e11450f295f39172b31defefb65b33bda18184"
      url "https://github.com/bspeelm/bothy/releases/download/v#{version}/bothy_linux_amd64.tar.gz"
    end
  end

  name "bothy"
  desc "A turn-key terminal workspace built from tools you already trust"
  homepage "https://github.com/bspeelm/bothy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bothy"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bothy"]
    end
  end

  # No zap stanza required
end
