# This file was generated by GoReleaser. DO NOT EDIT.
cask "bothy" do
  version "0.9.1"

  on_macos do
    on_arm do
      sha256 "60f290011742cad6206124553e646b01dd048a8eef0aec64adc1e40b56021a0c"
      url "https://github.com/bspeelm/bothy/releases/download/v#{version}/bothy_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d58967ed00594c32e499767ed3b6b2d5aecf3df6c1cbf1284ff99cd46151eb6c"
      url "https://github.com/bspeelm/bothy/releases/download/v#{version}/bothy_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "30cd2b96f8d70a27e27f164d98cd0158fef782688799b1f0288f8492914ec3a8"
      url "https://github.com/bspeelm/bothy/releases/download/v#{version}/bothy_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b9fd8580d7466bb4db21dac6d88dafa5392280fc177a2402a20cdb6cd42a09ea"
      url "https://github.com/bspeelm/bothy/releases/download/v#{version}/bothy_linux_amd64.tar.gz"
    end
  end

  name "bothy"
  desc "A turn-key terminal workspace built from tools you already trust"
  homepage "https://github.com/bspeelm/bothy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bothy"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bothy"]
    end
  end

  # No zap stanza required
end
